### ISSUE TITLE
Manufacturer / Model / Serial characteristic support.

### ISSUE THREAD

**Issue by hjdhjd** [hjdhjd/homebridge-doorbird#1]
Great plugin, works well.

I'd appreciate adding in proper support for Manufacturer / Model / Serial characteristics so those of us with multiple devices can better describe them to HomeKit. (e.g. D101 vs D202 Doorbird models).

**Comment by brownad** [comment]
I only did that to mark my motion sensor but there's no real discovery I will look at making it more generic for other units

**Comment by hjdhjd** [comment]
Just add in the ability to specify model / manufacturer / serial like most of the other plugins…seems like just a couple of lines of code, no?

**Comment by brownad** [comment]
Yeah that's possible I can move it to the config. This plugin is really just a stop gap to give some notifications to DoorBird ideally a plugin is made that brings together camera, sensors and a pseudo doorbell but that's a bit more to think about and needs audio to work to even be worth it - nothing I've seen yet

I'll make a change soon for the manufacturer and serial and default to the lowest option

**Comment by brownad** [comment]
That's done now, defaults back to the D101 if not supplied
