### ISSUE TITLE
slow/delayed stream and can't hide relay (D101)

### ISSUE THREAD

**Issue by paqpaqpaq** [hjdhjd/homebridge-doorbird#101]
Although snapshots are very very quick and accurate, opening a stream takes about 9 seconds, and then watch it with about a 4-5 seconds delay. That is quite long to actually receive some footage that was accurate 5 seconds ago.

Also when I hide the lock relay, Hide.Relay.1 the camera will not respond at all. 

Is there anything I can do to speed up the ffmpeg stream?

**Comment by hjdhjd** [comment]
Short answer: not at this time. I'm working on some things that may improve the situation in the future.

The problem is the Doorbird has an incredibly crappy H.264, to use a technical term. It's the culprit here.
