### ISSUE TITLE
Retry only once?

### ISSUE THREAD

**Issue by mbrackjr** [hjdhjd/homebridge-doorbird#107]
Hi!

First of all thanks a lot for great homebridge plugin. It's working quite fine for; would love to see a bit faster video and I hope you can get the audio-return working, than it's probably as best as Doorbird could do themselves (if they'd ever fulfill their promise, but not holding my breath..)

When power is interrupted, my doorbird seems to be retried only once and then the plugin crashes out and does not reconnect. Is this on purpose?  Can this behavior be changed/influenced with a parameter?

[10/17/2020, 4:57:42 PM] [Doorbird] Poort: Connection to Doorbird events API has been lost. Reconnection attempt in 2 minutes.
[10/17/2020, 4:59:45 PM] [Doorbird] ERROR: Name: request to http://xxx:xxx@192.168.0.130/bha-api/monitor.cgi?ring=doorbell,motionsensor failed, reason: connect EHOSTUNREACH 192.168.0.130:80, Message: %sFetchError

thanks!
Manfred

**Comment by hjdhjd** [comment]
Thanks for reporting it...I'm aware of the limitation and it's on the backlog. I've got a couple of other priorities for this plugin that I need to get over the finish line and will address this in time. For the time being - it's a one-shot deal. I get it's an inconvenience, but you really should have that power thing looked at. :smile:

**Comment by mbrackjr** [comment]
LoL; the power-thing happened once, so for troubleshooting i tried a few times manually ;-)
Great to hear you know about it already, looking forward to your updates, and again, kudos for the great plugin.
