### ISSUE TITLE
Schedule http calls vs. monitor.cgi

### ISSUE THREAD

**Issue by mrhund** [hjdhjd/homebridge-doorbird#111]
Hi guys, incredible things happened since I least checked the code of this plugin. Nice work 👍 

One thing I am not 100% happy about is the decision to remove the HTTP calls via the schedule function of the app and return to monitor.cgi. This not because the initial implementation has been done by me - it‘s because I am facing delays from sometimes > 10sec and sometimes even no notification on the mobile device. This never happened with the HTTP call implementation.

As I‘m not familiar with TS and I don‘t want to lose track of the other changes that you are doing, I want to discuss the possibility of maybe a switch and support both types of notification. I understand that monitor.cgi is easier for newbies, but maybe we can make an expert configuration using the HTTP calls. 

Any comments on that?

**Comment by hjdhjd** [comment]
@mrhund Thanks for the support. Didn’t know you were a previous contributor to the older versions of this plugin, prior to my ground-up rewrite. :smile:

As to monitor vs http - that’s not a path I’m likely to go back down. monitor.cgi is where we are, and will remain, unless there’s a good reason to look in another direction. If you’re having an issue with the monitor API, that’s either a bug in the Doorbird, a bug in this plugin, or an issue with your environment. Let’s figure that out, before looking at radical solutions like reintroducing a terribly un-user-friendly integration option, shall we? :smile:

If you have a testable use case that I can reproduce, happy to look into it further. Beyond that, I’d suggest taking a close look at your home network setup. First place I would look is if you’re using VLANs and how those VLANs are configured. There are known issues with Doorbirds and VLANs.
