### ISSUE TITLE
Explanation for cmd-* config values

### ISSUE THREAD

**Issue by RealDeemer** [hjdhjd/homebridge-doorbird#12]
I am wondering about the config values:

          "cmd_doorbell": "",
          "cmd_motionsensor": "",

I left them blank and and it did work. However, what is the purpose of this

**Comment by bombadiltom** [comment]
These commands are executed, when the doorbird raises the corresponding event.

**Comment by RealDeemer** [comment]
Does it mean that I can just add a wget to trigger another service or would this overwrite the default behavior?

**Comment by bombadiltom** [comment]
You can do this, as the default behavior is to do nothing. The commands are optional.
