### ISSUE TITLE
Forwarding events 

### ISSUE THREAD

**Issue by brownad** [hjdhjd/homebridge-doorbird#13]
@bombadiltom could you think of a sensible way to forward on receivers doorbell / motion events to another endpoint?

I’d like to notify my zipatile on each of these.  Unfortunately if I use the integration between the two it wipes out how we have the notifications registered here with this plugin.

**Comment by bombadiltom** [comment]
Doesn't zipatile support SIP for doorbell? 
Did you try Automation with an Apple TV/iPad?
Homebridge is a bridge, not a hub.
The command integration already is a hack ;-)

**Comment by bombadiltom** [comment]
Try this with nodered:
https://github.com/cflurin/homebridge-mqtt

**Comment by brownad** [comment]
Sip with DoorBird isn’t there yet.  Thanks for the link

**Comment by bombadiltom** [comment]
It's in BETA: https://www.doorbird.com/de/sip 
Works fine with my FRITZ!Box and FRITZ!Fone

**Comment by brownad** [comment]
Yeah I’ve seen that it’s more a problem on zipatile side
