### ISSUE TITLE
Doorbird Model 11v supports 1080p - would be great if this plugin could support this mode as well

### ISSUE THREAD

**Issue by tobiswelten** [hjdhjd/homebridge-doorbird#137]
Hey,

currently the plugin is not supporting 1080p streams coming from my Doorbird Model 1101.
The current API documentation is also not mentioning the URL for that stream, so I pinged the dev team and they gave me the following feedback:

MJPG/JPG - VGA
http://<device-ip>/bha-api/video.cgi
http://<device-ip>/bha-api/image.cgi

RTSP - 720p
rtsp://<device-ip>:<device-rtsp-port>/mpeg/media.amp

RTSP - 1080p
rtsp://<device-ip>:<device-rtsp-port>/mpeg/1080p/media.amp

i briefly checked it with FFmpeg on my machine and was able to get a 1080p stream from my camera. would be great if you could offer the better quality to the user as well, thanks!

Aside that - plugin works great - thanks!!!

Tobi

**Comment by hjdhjd** [comment]
In an upcoming release along with other goodies. 😄 

Thanks for the insight on the updated (and undocumented!) URLs.

**Comment by tobiswelten** [comment]
Great!
I know, awkward question but can I expect a change this month/year?

Tobi

Von meinem iPhone gesendet

**Comment by hjdhjd** [comment]
No comment. Cheers.
