### ISSUE TITLE
Night vision activated when relay is triggered

### ISSUE THREAD

**Issue by peer69** [hjdhjd/homebridge-doorbird#142]
Not sure if this is a bug or I got some setting wrong. Every time I trigger the Relay via HomeKit, night vision is activated. 
I found options to set for nightvision when a ring is detected but none for when a relay is triggered. 

> [11/26/2020, 11:48:57 AM] [Doorbird] Doorbird Vorgarten: Relay 1 unlocked.
>         [11/26/2020, 11:48:57 AM] [Doorbird] Doorbird Vorgarten: Doorbird night vision activated for 3 minutes.
>         [11/26/2020, 11:49:02 AM] [Doorbird] Doorbird Vorgarten: Relay 1 locked (auto-initiated after 5 seconds).

**Comment by hjdhjd** [comment]
Sure - please post your config and what you’re trying to do and let’s take a look!

**Comment by peer69** [comment]
That’s my config. I just want to be able to trigger the relay without activating the night Vision. 

>  {
            "doorbirds": [
                {
                    "ip": "192.168.x.x",
                    "username": "xx",
                    "password": "xx",
                    "name": "Doorbird Vorgarten",
                    "nightVisionSnapshot": false,
                    "nightVisionDoorbell": false,
                    "nightVisionVideo": false,
                    "nightVisionSnapshotNight": false,
                    "nightVisionDoorbellNight": false,
                    "nightVisionVideoNight": false
                }
            ],
            "platform": "Doorbird"
        }

**Comment by hjdhjd** [comment]
It's a bug...thanks for bringing it to my attention. Will be fixed in an upcoming release. Thanks!

Edit: not a bug.

**Comment by hjdhjd** [comment]
I stand corrected...it's working as intended.  :smile: The plugin will only turn on night vision (aka the infrared) if you configure it to do so. Are you certain that the plugin is turning on night vision?

**Comment by peer69** [comment]
Yes. Night vision is turned on every time I trigger the relay via HomeKit. 
How could I even configure the plugin to do so? I only see options to turn on night vision on ring events. Not when the relay is triggered.

**Comment by hjdhjd** [comment]
Given the log entries you posted, I suspect it is the plugin that’s doing it.. How did you configure it? I’d suggest that you use the Homebridge UI for optimal results.

Also, can you post the entries from Homebridge related to Doorbird when Homebridge first starts up. You should see something like:

```
[11/28/2020, 12:46:50 PM] [Doorbird] DoorBird D2101V: Night vision will be activated for doorbell events at night.
[11/28/2020, 12:46:50 PM] [Doorbird] DoorBird D2101V: Night vision will be activated for all snapshot requests at night.
[11/28/2020, 12:46:50 PM] [Doorbird] DoorBird D2101V: Night vision will be activated for video streaming at night.
[11/28/2020, 12:46:50 PM] [Doorbird] DoorBird D2101V: Connected to the Doorbird events API.
```

if the plugin is in fact configured for night vision.

Thanks.

**Comment by peer69** [comment]
I do use homebridge-ui-x to configure. Thats what I see on HB startup: 

> [12/6/2020, 7:05:27 PM] [Doorbird] Initializing Doorbird platform...
> [12/6/2020, 7:05:27 PM] [Doorbird] Doorbird Vorgarten: Detected relay: 1 (primary).
> [12/6/2020, 7:05:27 PM] [Doorbird] Doorbird Vorgarten: Connected to the Doorbird events API.

From what I can tell I have not configured anything related to night vision. At least I have not set anything to true after I tried setting everything to false to fix this. 
From what I can see the plugin still activates night vision as soon as the doorbell rings. This is not a problem at night as it is already on but its quite annoying during the day when several persons ring during the 3 minutes the night vision is activated each time.
