### ISSUE TITLE
Doorbird is not working

### ISSUE THREAD

**Issue by sohnkarlsruhe** [hjdhjd/homebridge-doorbird#15]
First thanks for your work. I install this plugin and camera-ffmpeg (is working)
but door bird is shown in home app but nothing happens (push the button or the motion sensor.

here is my config.json

 {
            "platform": "DoorBird",
            "doorbird": [
                {
                    "name": "DoorBird",
                    "doorbird_ip": "192.168.0.105",
                    "doorbird_username": "ghXXX02",
                    "doorbird_password": "bdXXXXx2t",
                    "doorbird_model": "D101S",
                    "doorbird_serial": "4260423860193",
                    "cmd_doorbell": "",
                    "cmd_motionsensor": "",
                    "http_port": "8080"
                }
            ]
        },
        {
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "name": "Doorbird Camera",
                    "videoConfig": {
                        "source": "-re -i rtsp://ghXXX02:bdXXXX2t@192.168.0.105:554/mpeg/media.amp",
                        "stillImageSource": "-i http://gXXXX002:bXXXX2t@192.168.0.105/bha-api/image.cgi",
                        "maxStreams": 1,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 15

**Comment by bombadiltom** [comment]
What do you expect to happen? Both are only Sensors, you need to define an Automation.
Can you switch on the Camera Light?
What's in the logs?

**Comment by sohnkarlsruhe** [comment]
now i can see in the home app when the doorbell button is pushed.. but only when i add "cmd_doorbell": "", the wget command. Motion Sensor don't work with the wget command .

when i push the doorbell button:

`[2017-7-27 17:27:40] HTTP Server: doorbell.html was called, sending event to homebridge.
[2017-7-27 17:27:40] undefined
[2017-7-27 17:27:40] HTTP Server: executing 'wget -q 'http://192.168.0.105/bha-api/notification.cgi?http-user=gxxxxx2&http-password=xxxxbell&subscribe=1&url=http://192.168.0.115:8080/doorbell.html''
`

and i can see it in the home app...
but the motion sensor is not working, in the doorbell app i see the motion
if i activate the doorbell light:
`[2017-7-27 17:30:47] DoorBird night vision activated for 3 minutes`

**Comment by brownad** [comment]
Post your config from the doorbird api eg call the notification.cgi? And drop the Json here

**Comment by bombadiltom** [comment]
Do not add
"cmd_doorbell": "",
"cmd_motionsensor": ""

Leave the lines out!
The code checks, if these values are defined and if they are, they must contain valid commands!

**Comment by sohnkarlsruhe** [comment]
sorry.. when i leave them blank or delete the 2 lines nothing happened when i am in front of the sensor or ring the bell.

**Comment by brownad** [comment]
Have you done the one off step to register the doorbird with the two endpoints in your Pi?

Eg for the doorbell and the motion sensor html entries?  There is a comment on the readme for this, that will then tie up the plugin with the events from DoorBird.

Does that make sense?

**Comment by unaxboy** [comment]
Hi brownad, how to register endpoints?

**Comment by brownad** [comment]
It’s on the readme. You need to put the IP of your running Homebridge and the IP of your doorbird - just uses the doorbird api notification endpoint 

That’s it

**Comment by unaxboy** [comment]
Thanks, already found by myself)
