### ISSUE TITLE
Stream load very long and bad video quality

### ISSUE THREAD

**Issue by BlackJoker90** [hjdhjd/homebridge-doorbird#151]
I have some trouble with the latest version of the doorbird plugin. I can see the video stream in my HomeKit but the video quality is bad and the stream load very long. Sometimes it even shows nothing.

I get these errors in my Homebridge Status:
[08/12/2020, 01:23:15] [Doorbird] Doorbird: HomeKit video stream requested: 1920x1080, 30 fps, 802 kbps.
[08/12/2020, 01:23:15] [Doorbird] Doorbird: **ffmpeg exited with code: 1 and signal: null (Error)**

Here is my config:
https://forum.smartapfel.de/attachment/11655-pasted-from-clipboard-png/

**Comment by tobiswelten** [comment]
Hey, just a comment from my side. I do have a D11 and a similar issue not only with this plugin also with other tools like e.g. "MotionEye".
By contacting the Doorbird support they admit that especially in low light situation there is an issue with keeping the stream stable with non-corrupt data packages. The result of that issue might vary on the config of your codec but in my case I see no stream throughout the night at all.

BTW, based on the Doorbird API documentation the max. fps the doorbird can provide is 12fps. Don't know how important that is but something to reduce eventually.

**Comment by BlackJoker90** [comment]
Hey thanks for the input I'm pretty sure that this could be a reason for my issues. In my Synology DS Cam everything is looking very good and stable and there my cam is set up at 1280x720@10 FPS but I have no idea how to tweak that settings for the doorbird plugin in my homebridge.

**Comment by tobiswelten** [comment]
The only I think I suggest is to send a mail to the doorbird support with your problem and eventually point to my ticket number Ticket#2020111822000501] about this.
They told me they working on a fix but I just send them a mail this morning to ask about the status of that issue. Eventually we get a little Christmas present from them soon.

**Comment by BlackJoker90** [comment]
Thanks I just send them a message as well and refered to your ticket but that won't solve my issue with the plugin and the error message of ffmpeg.

**Comment by hjdhjd** [comment]
I'm overdue to push an update I've been working on that should help. I'm hoping to get this out over the holidays guys...stay tuned.

The slow stream start time sucks, but as someone mentioned, it's a difficult one to overcome. There are a few options though, to alleviate some of this and I hope to have it in the upcoming update.

Thanks!

**Comment by BlackJoker90** [comment]
That sounds great looking forward for that update :) btw I found out that the stream load much faster when Im not in my private network. When I check the cam with my Phone in 4G network the stream loading time is better just to let you know.

**Comment by tobiswelten** [comment]
Possible that you request the non HD stream over cellular? Also QoS Setup ( Codec, etc) can be different.

**Comment by BlackJoker90** [comment]
Possible yes but I have no chance to check which stream I'm requesting. I got also a response from the Doorbird support, and they told me that the poor video quality during the night is a known problem of the HD Stream (RTSP) especially of the D11x series. They're working on a fix already which maybe will be released during holidays or January 21. So a new doorbird plugin and the new firmware for the doorbird itself maybe will fix this.

**Comment by tobiswelten** [comment]
There is only he icon in the top right corner, above the video stream. Within LAN it shows „HD“ to me. That is the only place I can think of right now.
Yeah…the D11x series has some problem when it comes to low light scenario. Maybe its all connected to each other.
