### ISSUE TITLE
New to Hoobs,  Isssues adding doorbird

### ISSUE THREAD

**Issue by mkattan1992** [hjdhjd/homebridge-doorbird#162]
Hi,
I just purchased hoobs aand uploded to latesst release 3.3.1. i have 2 doorrbird systems and downloaded the plugin s/w, but do not know how to proceed further. appreciatee your guidance herer. homebridge does show in my homekit aas a bridgee, but not  the accessory yet.
thanks

**Comment by hjdhjd** [comment]
Hi! Welcome to the Homebridge ecosystem. Unfortunately, I don't use HOOBS, I use Homebridge directly (which also has a nice webUI) so I'm afraid I can't help you track down the details within HOOBS. Essentially, you need to configure the plugin. There should be a webUI within HOOBS that you can use.

Take a look at the HOOBS documentation on configuring plugins: https://support.hoobs.org/docs/5e7644ece87d1e02b6c19d42

Hope it helps.

**Comment by mkattan1992** [comment]
thanks a lot for the prompt response. will do and will revert back. happy
to follow the same process as Homebridge as i beleive they are similar.
would be great if you could share also the Hombridge plugin config for
doorbird.
thanks !
Moustafa
