### ISSUE TITLE
Microphone and Speaker

### ISSUE THREAD

**Issue by jannnfe** [hjdhjd/homebridge-doorbird#18]
I am excited about this plugin. I have not found a comparable one yet. However, I have a few questions that you may be able to answer.
I do not have a Doorbird bell but since the project is open source I would like to try to build the plugin for my purposes if that's okay.
I wonder if the intercom is really working at the moment? If so, how exactly do microphone and speakers work? Is there a way to test this function without a Doorbird?
Thanks!

**Comment by brownad** [comment]
Hi

Feel free to take the ideas further.  Not sure what you want to bring together in terms of hardware. 

You won’t be able to test without a DoorBird unless you modify the urls inside the code to whatever device you need or have.  And then handle the responses accordingly.  This works based on events from DoorBird back to the homebridge client eg the notification api given by DoorBird so it’s custom.

At the moment as mentioned intercom doesn’t work, as this isn’t supported by ffmpeg. 

You can see a working speaker / microphone on the foscam project this might be a good start.  I’m hoping for some help to get audio working so for now it’s a demonstration of video stream with embedded doorbell, the motion sensor events from the doorbird motion sensor plus the funky lock and light it offers.

Have a look at the samfox2 project this has the more straight forward example if you just want a camera and doorbell. But the mic and speaker is commented out.

**Comment by jannnfe** [comment]
Thank you for the fast answer. The [Samfox2](https://github.com/Samfox2/homebridge-doorbell) plugin is indeed easier and more universal. Thank you for this hint.

**Comment by brownad** [comment]
Yeah it’s a simple starter I had more things to add to DoorBird. 

Good luck

**Comment by jannnfe** [comment]
Sorry that I have to ask something again. I did not want to open a new topic, so I'll ask it here again. I'm just about to understand the functions of the doorbell. Actually, the ProgrammableSwitchEvent should give a notification when the status changes and the notification "Ringing the bell" should appear on the iPhone. Why does not that work for me?

EDIT: Is the Doorbell Notification only possible with the Video Camera?

**Comment by brownad** [comment]
Hi

Do you have a doorbird device? The plugin is only for doorbird.  If you’ve setup the plugin correctly, you’ll see the video, and other accessories appear. The doorbell part is not visible in home app, it’s simply part of the video and yes it fires an event to iOS on ring automatically with no further config needed for a ring notification.  You doo need to register your doorbird notification API to your running homebridge device again in the docs. As it needs to know where to send the events to.

Hope this helps

**Comment by jannnfe** [comment]
Yes, I know that this plugin is specially tuned to doorbird. I personally do not have a doorbird but I would like to try your plugin to make it fit my purpose. Since I do not have much clue about programming, I'm trying to get a working doorbell running with MQTT and Node-Red.
I do not understand exactly when the service Doorbell sends a notification to Homebridge. Whenever its value changes automatically or does the event have to be called explicitly with a line of code?

**Comment by brownad** [comment]
Look at this

https://github.com/Samfox2/homebridge-videodoorbell

It’s simpler
