### ISSUE TITLE
Syntax error 

### ISSUE THREAD

**Issue by jbk1988** [hjdhjd/homebridge-doorbird#186]
I had to clear my cache because of another Homebridge device, and now, I’m not getting notifications for motion or doorbell.

the error is: /bin/sh: 1: Syntax error: Unterminated quoted string

I didn’t change a thing, any pointers?

**Comment by hjdhjd** [comment]
This doesn’t appear to be a plugin-related bug. My guess is there’s something up in your startup scripts, or homebridge configuration.
