### ISSUE TITLE
update on video quality with Doorbird D1101V

### ISSUE THREAD

**Issue by axelbrunger** [hjdhjd/homebridge-doorbird#189]
Just to let you know, the only way that I get reasonable video quality involves removing audio altogether (by specifying an FFmpeg executable without the libfdk-acc support, and by using the following FFmpeg options:

-preset ultrafast 

(instead of -preset veryfast)

and 

-tune zerolatency

Hope you find this useful.

Axel

**Comment by hjdhjd** [comment]
I’ve already stated this elsewhere in responses to other issues. :smile:

**Comment by axelbrunger** [comment]
I agree, removing audio helped a lot. Thank you.  I just wanted to point out that the "-preset ultrafast" and "-tune zerolatency" made things even better with the DoorBird DV1101V (video less choppy, no freezes, and shorter initial latency).
