### ISSUE TITLE
Door lock support.

### ISSUE THREAD

**Issue by hjdhjd** [hjdhjd/homebridge-doorbird#2]
As you continue to evolve the plugin, door lock support would be terrific to see added. The API reference seems pretty straightforward, it's a matter of making the door lock component "visible" to HomeKit / homebridge.  Thoughts?

Relevant API:

http://<device-ip>/bha-api/open-door.cgi

Returns on success:

{
"BHA": {
"RETURNCODE": "1"
 }
}

**Comment by brownad** [comment]
Can be done

**Comment by brownad** [comment]
I think adding a switch component but would need to poll for status periodically to see if another device has changed its state. I don't have a lock but can look at it sometime soon

**Comment by hjdhjd** [comment]
I suspect you don’t actually need to have the lock to trigger / test it. You can trigger the “unlock” action from the Doorbird app or the web interface. I don’t think a “switch” type is right though…it would be a “LockMechanism” type. See the August homebridge or homebridge-httplock as examples…

Thoughts?

**Comment by brownad** [comment]
Yep I know the idea, not difficult I'll have a look and will probably publish this in npm properly

One problem I have is the sensors keep on dropping out you might notice this not a plugin problem but something on HAPjs

**Comment by brownad** [comment]
I have added the 'open door', night vision and motion sensor in this change.  Have a look its a bit rough, the button event reset since they never detect state.

**Comment by brownad** [comment]
Leaving as door service for now, lockmechanism would be better but a change in the plugin is needed

**Comment by brownad** [comment]
thanks for the link mention on the wiki ;) @hjdhjd 

Hope its all working for you.  I'm thinking about some fundamental changes to make this a real video doorbell whereby:

IP Camera stream includes a Doorbell service
Motion sensor is provided
Door lock service provided
Remove need for night vision... you get it for free in the doorbird at night time automatically, don't think there's much need for it

Now I need some serious time to work out the above :|
