### ISSUE TITLE
homebridge-doorbird with homebridge-camera-ffmpeg issues

### ISSUE THREAD

**Issue by brownad** [hjdhjd/homebridge-doorbird#25]
Might need some extra help, or clarification.

Running the plugin with `homebridge-camera-ffmpeg` causes the doorbird video stream to Exit out when you want to see the video.  But in standalone testing I noticed its possible to do the same to the `homebridge-camera-ffmpeg` and receive the doorbird video without fail, so not clear why they can't for some reason co-exist as separate plugins, its been that way for a while for me.

Any ideas out there?

**Comment by mrhund** [comment]
Only a first guess, maybe something with the order of adding the devices or calling the events...? Or with the timing of the events....?
In one of your last posts you wrote something about iOS 12 Beta... is it only with the Beta...? I’m asking cause I don‘t have any issues.

**Comment by brownad** [comment]
It’s not the beta it was a thought initially, however I did want to bring ffmpeg in line.

It’s easier to see it fail now post upgrade - Exit Code 1. I’ll check order of devices, either that or run separately.

**Comment by brownad** [comment]
Fixed by adding and re adding the video source odd but what the ..
