### ISSUE TITLE
No Doorbird accessory

### ISSUE THREAD

**Issue by Nijneman** [hjdhjd/homebridge-doorbird#27]
I've installed the DoorBird plugin, homebridge starts en loads the plugin.
Message: Initializing DoorBird Platform is displayed, but that's it...

What info do you need to help me search for the error i might have made?

**Comment by brownad** [comment]
Have you added the accessory in HomeKit, e.g. its discovered or you ran manual discovery (with your PIN) and added the camera along with the accessories that come with it; motion sensor, light and lock?

Also paste your config for the plugin you added please.

**Comment by cloudz** [comment]
I'm having the same issue. Running HomeBridge in a docker container on Synology. ffmpeg is installed. 
The other accessories on homebridge are added but those of Doorbird don't show up. 

```
[11/25/2018, 6:08:02 PM] [mPower] Initializing mPower platform...
[11/25/2018, 6:08:02 PM] [mPower] Initializing platform accessory 'Buitenverlichting'...
[11/25/2018, 6:08:02 PM] [mPower] Initializing platform accessory 'Kerstboom 1'...
[11/25/2018, 6:08:02 PM] [mPower] Initializing platform accessory 'Kerstboom 2'...
[11/25/2018, 6:08:02 PM] [DoorBird] Initializing DoorBird platform...
[11/25/2018, 6:08:02 PM] Loading 1 accessories...
[11/25/2018, 6:08:02 PM] [Garage] Initializing PhotonGarageDoor accessory...
```

I've been looking for errors in logs but can't seem to find anything.

**Comment by brownad** [comment]
Share you config please

**Comment by cloudz** [comment]
```
 {
            "platform": "DoorBird",
            "cameras": [
                {
                    "name": "DoorBird",
                    "doorbird_ip": "192.168.x.xx",
                    "doorbird_username": "user",
                    "doorbird_password": "pass",
                    "cmd_doorbell": "",
                    "cmd_motionsensor": "",
                    "videoConfig": {
                        "source": "-re -f mjpeg -i http://user:pass@192.168.x.x/bha-api/video.cgi",
                        "stillImageSource": "-i http://192.168.x.x:80/bha-api/image.cgi?http-user=user&http-password=pass",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 15,
                        "port": 5005
                    }
                }
            ]
        }

```

**Comment by brownad** [comment]
going to ask a silly question, looking at the above it looks good but have you actually added the camera device to HomeKit? Cameras are a bit different, and you need to add it along with the PIN again.  If your config is complete, and you've wired up the DoorBird API to notify your device, which you can test by going to the URL you entered into your Motion target.  If you haven't added the device then very little will happen, its not like the normal Homebridge devices that just show up.  So do have a look if you can add it, discover it then see...

**Comment by cloudz** [comment]
It's not a silly question. I wasn't aware. Thanks! (maybe add it to the install instruction :))

**Comment by brownad** [comment]
Added, hope it works :+1:
