### ISSUE TITLE
Integrating with the cloud API?

### ISSUE THREAD

**Issue by matthew-gerstman** [hjdhjd/homebridge-doorbird#28]
Has anyone had any luck integrating with the actual doorbird cloud API?

My landlord installed doorbird for our entire building so I don't have direct access to the network the unit is on. He's having us use the doorbird iOS app but it's atrocious. I'm hoping to integrate with my existing doorbird setup.

Anyone know where to start?

**Comment by brownad** [comment]
Cloud api isn’t available to the public.

TBH if it’s multi tenant then this plugin has no concept of multi tenant at all

Sorry

Hopefully one day doorbird will make it supported with homekit fully

**Comment by brownad** [comment]
Not going to happen, cloud API is closed to me
