### ISSUE TITLE
Doorbird D21 series - second Lock

### ISSUE THREAD

**Issue by Alcor72** [hjdhjd/homebridge-doorbird#30]
Hi,

I've just got a D2101v intercom from Doorbird.
I used the Homebridge-doorbird plugin (Homebridge working on Synology NAS) and almost everything works fine.
The issue for me is that I cannot control the second Lock (this intercom model has 2 locks).

I tried to modify the plugin from brownad with out success till now.

Anyone has the same issue?
Thanks in advance for the support.

**Comment by brownad** [comment]
I think it would need to be configurable to add a second lock for these kind of devices, I would welcome a PR from anyone that is interested

**Comment by thevangogh** [comment]
Hi Alcor72,
I had the same issue.

I implemented a workaround using "Homebridge Webhooks". Create a virtual Push Button that calls the  Doorbird API to trigger the second relay.

Regards

**Comment by brownad** [comment]
This could be added in as a second door lock but better to be optional in config

I’ll look at it sometime - PRs welcome though

**Comment by Alcor72** [comment]
Hi thevangogh,

I worked on it today but could not work out the correct way of using the Push Button.
Got the following error  (see attach).
My config.json is :
{
        "platforms": [
            {
                "platform": "HttpWebHooks",
                "webhook_port": "51828",
                "pushbuttons": [
                    {
                    "id": "pushbutton1",
                    "name": "Push button name 1",
                    "push_url": "http://192.168.86.XXX/bha-api/open-door.cgi?r=2&http-user=USERNAME&http-password=USERPASS",
                    "push_method": "GET"
                    }
                ]
            }
        ]
    }
Could you help?
Thanks in advance 
/usr/local/lib/node_modules/homebridge/lib/api.js:108 | stdout
-- | --



/usr/local/lib/node_modules/homebridge/lib/api.js:108 | stdout
-- | --


[RenergiseBackup - Synology DiskStation.pdf](https://github.com/brownad/homebridge-doorbird/files/2727492/RenergiseBackup.-.Synology.DiskStation.pdf)

**Comment by brownad** [comment]
Might be easier to get help on the plugin issue board 

But have you tried to run the plugin without the push button configured, then tested out the URL request separately (assume that works)?

Then introduce the push button one config at a time.

**Comment by thevangogh** [comment]
Alcor,
The Doorbird URL looks correct. Have you tested it directly using a browser? 

re: HttpWebHooks, based on the output error, I suspect it's the HttpWebHooks plugin issue. As Brownad suggested, were you able to get HttpWebHooks plugin up on itself?

I do have an extra entry after webhook port
"cache_directory": "./.node-persist/storage",
Not sure if that will help you.

Regards,

**Comment by bowana** [comment]
Did anyone get this working?  I actually have 3 doors running off my DoorBird ( I have the IO unit) and would value being able to select different locks to expose to HomeKit.

**Comment by Gordoncj82** [comment]
+1
This would be so helpful for me too. I can currently only control one of the two gates. 
Would very much appreciate this addition.

**Comment by karad0** [comment]
+1

**Comment by thevangogh** [comment]
Httpwebhooks definitely works. Try it out independently from the doorbird plug-in first.
