### ISSUE TITLE
Video streaming only works on local network

### ISSUE THREAD

**Issue by BillS11** [hjdhjd/homebridge-doorbird#32]
I’m running homebridge from my iMac. When I’m on the same wifi network as my iMac i.e. at home, all my iDevices are able to stream the video in the Home app. However, when I’m on 4G or another wifi network, the video tries to load and then eventually times out after 30 seconds.

The log below looks fine though. I’ve tried removing and re-adding the camera in Home app but to no avail. 
```
[2/7/2019, 12:10:13 AM] [DoorBird] Start streaming video from DoorBird with 1280x720@299kBit
[2/7/2019, 12:10:43 AM] [DoorBird] Stopped streaming
```

Definitely related to this is the fact that when I force-touch the lock screen notifications, the expanded picture doesn’t turn into a live video stream unless I’m on the same wifi network as my iMac running Homebridge. 

Any ideas?

**Comment by brownad** [comment]
Same happens with other ffmpeg streams anything can stop it from streaming

**Comment by mrhund** [comment]
I can confirm the behaviour. Its not stopping from external network - it does not even start streaming. In my case there is no request in the log so obviously the request is not routed correctly to the homebridge plugin...

**Comment by brownad** [comment]
I just don’t see this at all
