### ISSUE TITLE
Error with multiple Doorbirds

### ISSUE THREAD

**Issue by zork17** [hjdhjd/homebridge-doorbird#33]
When I add a second Doorbird device I get an error:

```
17:22:42 RSBPI homebridge[18205]: /usr/lib/node_modules/homebridge/lib/server.js:515
Feb 24 17:22:42 RSBPI homebridge[18205]: throw new Error("Camera accessory " + accessory.displayName + " experienced an address collision.");

```
Why is there a collision when the names of both devices are different and also their IPs?

**Comment by brownad** [comment]
Post confit please however this was never tested with more than one doorbird as the endpoint is hard coded as I remember. Do you have a doorbird and a doorbird guard?

**Comment by zork17** [comment]
This is the config file:
```
{
      "platform": "DoorBird",
      "cameras": [
        {
          "name": "Gate",
          "doorbird_ip": "10.0.0.68",
          "doorbird_username": "XXX",
          "doorbird_password": "YYY",
          "cmd_doorbell": "",
          "cmd_motionsensor": "",
          "videoConfig": {
            "source": "-rtsp_transport tcp -re -i rtsp://XXX:YYY@10.0.0.68:8557/mpeg/media.amp",
            "stillImageSource": "-i http://10.0.0.68:80/bha-api/image.cgi?http-user=XXX&http-password=YYY",
            "maxStreams": 2,
            "maxWidth": 1280,
            "maxHeight": 720,
            "maxFPS": 15,
            "port": 5005
          }
        },
        {
          "name": "Door",
          "doorbird_ip": "10.0.0.65",
          "doorbird_username": "AAA",
          "doorbird_password": "BBB",
          "cmd_doorbell": "",
          "cmd_motionsensor": "",
          "videoConfig": {
            "source": "-rtsp_transport tcp -re -i rtsp://AAAA:BBB@10.0.0.65:8557/mpeg/media.amp",
            "stillImageSource": "-i http://10.0.0.65:80/bha-api/image.cgi?http-user=AAA&http-password=BBB",
            "maxStreams": 2,
            "maxWidth": 1280,
            "maxHeight": 720,
            "maxFPS": 15,
            "port": 5005
          }
        }
       ]
}

```
I have 3 Doorbirds and I tried to setup only 2 of them in Homebridge.
I also tried with a different port than 5005 for the second Doorbird because I thought that caused the collision, but it didn't work.

**Comment by zork17** [comment]
Any help?

**Comment by brownad** [comment]
It requires a re-write of key pieces to support multiple end points.  Pull request always welcome

**Comment by mrhund** [comment]
You definitly need to take different vales for "Port" as there are webservers created that listen for events (webhook) and trigger actions. But this is not the cause of the error above. The error says that there is an address conflict within homebridge. I am suprised about that as the UUID is created from the name and thery are different in your config:
`var uuid = UUIDGen.generate(cameraName);
var doorBirdAccessory = new Accessory(cameraName, uuid, hap.Accessory.Categories.VIDEO_DOORBELL);`
Some extra debug output would be helpful...

**Comment by zork17** [comment]
How can I provide more debug info?

**Comment by mrhund** [comment]
Unfortunately only be adding debug Information to the code.


Am 03.03.2019 um 12:10 schrieb zork17 <notifications@github.com<mailto:notifications@github.com>>:


How can I provide more debug info?

**Comment by zork17** [comment]
1) Can you please tell me what additional information to print?
2) Do I need to recompile the code? If yes, how to do that? Can you point me to an article about that?

**Comment by zork17** [comment]
Is there a way to duplicate this plugin with a different name (like homebridge-doorbird2 and platform DoorBird2) so I can have 2 Doorbirds in my Homekit setup using 2 platforms?
Something like this:
{
      "platform": "DoorBird",
      "cameras": [
        {
           ...
            "port": 5005
         }
       ]
},
{
      "platform": "DoorBird2",
      "cameras": [
        {
           ...
            "port": 5006
         }
       ]
}

**Comment by bombadiltom** [comment]
You could copy the whole repository locally and change this line in index.js
`  homebridge.registerPlatform("homebridge-doorbird", "DoorBird", doorBirdPlatform, true);`
to
`  homebridge.registerPlatform("homebridge-doorbird2", "DoorBird2", doorBirdPlatform, true);`

Then run "npm install -g ." in this directory.

**Comment by zork17** [comment]
@bombadiltom 
I tried it but now the system crashes even with one Doorbird.
Maybe I also need to change package.json ? I can see a reference there to Doorbird.
Also what about:
```
  "repository": {
    "type": "git",
    "url": "git://github.com/brownad/homebridge-doorbird.git"
  },
```

**Comment by bombadiltom** [comment]
Never tried it, was just an idea

Best mobile regards,

Tom Lorenz

**Comment by zork17** [comment]
it worked after also changing Doorbird to Doorbird2 in package.json
