### ISSUE TITLE
Complex situation

### ISSUE THREAD

**Issue by 19kirk79** [hjdhjd/homebridge-doorbird#34]
Dear community,

I use from doorbird just the bell trigger and the intercom.
As video source I use a Ubiquiti G3 working in homekit with homebridge-camera-ffmpeg-ufv plugin.
Is it possible to work with that?

And the second "issue" I have (that to be hones noone else in the world will have :)):
The doorbird is part of my KNX/Loxone homeautomation.
Means that I also do not use doorbirds motion senor and lock relay. Can I somehow "hack" the code to use this? In general its already working in Homebrigde through homebridge-loxone-ws that pulls all my smarthome components from Loxone to Homebridge. But i.e. doorlock shown as switch not as lock. Would be very nice if I could use the funcionalitys of the the doorbird plugin. But thats just a dream :)

Regards and thanks for your help!

**Comment by brownad** [comment]
Sorry, not planning to do anything like the above.
