### ISSUE TITLE
no notification

### ISSUE THREAD

**Issue by sevatrofimov** [hjdhjd/homebridge-doorbird#35]
when I call doorbell.html - in homebridge log file occur following string, but no notifications occur on iPhone/Mac:
[2019-3-23 18:56:05] HTTP Server: doorbell.html was called, sending event to homebridge.
[2019-3-23 18:56:05] undefined
notifications for motion sensor are enabled

**Comment by brownad** [comment]
Check your endpoint, and check you added this to the DoorBird (app) as an endpoint
