### ISSUE TITLE
Different port each startup

### ISSUE THREAD

**Issue by bleistift2** [hjdhjd/homebridge-doorbird#36]
Hi,

thank you for the plugin, I'm using it with a D301 and it works great.
Unfortunately the plugin is using a different port after each restart ("DoorBird is running on port ...", not the one it is listening on). Since my Homebridge is located in a docker container on a Synology NAS I have to re-configure the firewall each time to keep it working.

Is there a way to specify the port?

Another small issue, since the D301 doesn't support a camera I'm only using the lock, is there a way to delete/hide the camera and motion sensor devices in HomeKit but keep the lock?

Thanks in advance for the support.

**Comment by bombadiltom** [comment]
As the port is a camera and your device does not support one, why do you need access to it?
Anyway, at the moment, the port given in videoconfig is used for the webserver. This could be changed to a new config value and the given port could be used for the camera.

Also, at the moment the camera is always created, but as the device type is a config value, this could be implemented with some if statements...

Are there any other doorbird devices without camera?

**Comment by bleistift2** [comment]
Thanks for your answer.
I don't know about other Doorbird devices without a camera other than the D301 at the moment but the updated D302 has been announced a while ago.
The plugin informs about two ports at startup: "DoorBird is listening on port XXXX" and "DoorBird is running on port YYYY"
I've managed to set the XXXX port (is that the webserver?) in the config but I haven't found a value to set the port YYYY the Plugin is running on. Each startup it states a different port.
My problem is that without the YYYY port accessible all 3 HomeKit devices (lock, camera and motion sensor) are marked as "not available" even if the webserver port XXXX is accessible.
Unfortunately I'm new at using homebridge, what do you mean with if statements?

**Comment by mrhund** [comment]
The XXXX Port is the Webserver, which is used for forwarding the events and can be configured in the config file. The other Port (YYYY) is assigned by Homebridge dynamically at startup and afaik cannot be set to a fixed port.

Von meinem iPad gesendet

Am 08.08.2019 um 22:17 schrieb bleistift2 <notifications@github.com<mailto:notifications@github.com>>:


Thanks for your answer.
I don't know about other Doorbird devices without a camera other than the D301 at the moment but the updated D302 has been announced a while ago.
The plugin informs about two ports at startup: "DoorBird is listening on port XXXX" and "DoorBird is running on port YYYY"
I've managed to set the XXXX port (is that the webserver?) in the config but I haven't found a value to set the port YYYY the Plugin is running on. Each startup it states a different port.
My problem is that without the YYYY port accessible all 3 HomeKit devices (lock, camera and motion sensor) are marked as "not available" even if the webserver port XXXX is accessible.
Unfortunately I'm new at using homebridge, what do you mean with if statements?

**Comment by bombadiltom** [comment]
Fixed camera port is possible:
https://github.com/nfarina/homebridge/issues/927

**Comment by bombadiltom** [comment]
BTW: "if statements" are not user related, this would have to be implemented in the source

**Comment by bleistift2** [comment]
Thank you for the link and the information.
Unfortunately I didn't manage to get it working so far.
server.js already had a port parameter, I nevertheless added another, so it looks like this:
    ```hapAccessory.publish({
      username: advertiseAddress,
      pincode: accessoryPin,
      category: accessory.category,
      port: accessoryPort,
      port: accessory.cameraSource.port,
      mdns: this._config.mdns
    }, this._allowInsecureAccess);```
Since I don't have a camera and therefore don't have ffmpeg installed I didn't know where to add
`ffmpeg.js -> this.port = cameraConfig.portc;`
and added
`"accessory.cameraSource.port": 5000`
directly under the camera listening `"port": 5001` in the config.js.
Since that didn't work, what's the right way to do it?
Are the 2 port parameters in server.js the problem?
How do I define the parameter in config.js?

**Comment by bombadiltom** [comment]
Changing the config.js is not enough, all referenced issues refer to different versions of ffmges.js, so at first the latest version of ffmeg.js would have to be integrated. 

What about just commenting out those three lines:
`
 // Setup and configure the camera services
var cameraSource = new FFMPEG(hap, cameraConfig, self.log, videoProcessor);
doorBirdAccessory.configureCameraSource(cameraSource);
`
But as the whole thing is added as a video doorbell, I do not know, how HomeKit reacts to this.

**Comment by bleistift2** [comment]
Unfortunately commenting out these lines results in the whole plugin refusing to start.
So it seems like in order to fix the port of the Doorbird plugin I'll have to install the otherwise not needed ffmpeg plugin and try the way suggested in the other thread. I'll try it some day next week, thank you.
