### ISSUE TITLE
Doorbird not working after Homebridge update.

### ISSUE THREAD

**Issue by Jaymacgarcia** [hjdhjd/homebridge-doorbird#368]
Since last update, interface has frozen and is not updating anymore. Just wondering if there’s a fix for it..

**Comment by GuusSurtel** [comment]
Same issue here. After update of HomeBridge the Plugin of Doorbird doesn't work anymore.
Any hints how I can solve it?

**Comment by endquote** [comment]
@hjdhjd Curious if you're still working on this.
