### ISSUE TITLE
HomeKit Secure Video

### ISSUE THREAD

**Issue by jbk1988** [hjdhjd/homebridge-doorbird#378]
Hi,

I see that Homebridge FFMPEG is on the cusp of figuring out HomeKit Secure Video. If they succeed, can this be integrated into the Doorbird plugin? Thank you!

https://github.com/Sunoo/homebridge-camera-ffmpeg/pull/1200

**Comment by hjdhjd** [comment]
Nope. And they’re not either…least not yet.:smile:

It’s a ways off. When Homebridge finishes implementing HKSV, which will happen in the coming weeks / months, all the camera-related plugins I write and maintain will get this support…but don’t hold your breath on anything being imminent - we’ve all been working on this for some time to get to this point. :smile:
