### ISSUE TITLE
Doorbird with Second cam

### ISSUE THREAD

**Issue by sohnkarlsruhe** [hjdhjd/homebridge-doorbird#38]
I would like to use doorbird with a 2nd homekit compatible camera. can I disable the integrated doorbird kamers in homebridge and only use the doorbird Button to Fire Events? HTTP-doorbell is Not working.

**Comment by brownad** [comment]
Not sure what you mean what actual feature do you want here?  A motion sensor and another camera?

**Comment by sohnkarlsruhe** [comment]
I want to use the doorbird bell Button with an Logitech Circle 2 HomeKit cam. When i push the Button, Display the video of the doorbird cam. The Order cam is in the Same room

**Comment by brownad** [comment]
Use this it’s more generic:

https://github.com/Samfox2/homebridge-videodoorbell

But I’m not sure it will work fully. I don’t know the Logitech cam well

**Comment by sohnkarlsruhe** [comment]
Thanks for the fast answer, i only Need the Doorbell Service in Homebridge. The Logitech cam is HomeKit compatible

**Comment by brownad** [comment]
Sure but a doorbell service only works with a camera it’s a video doorbell service there’s no supported doorbell service anymore so you’d need to bend a plug-in to do what you need it won’t show up as a button it’s embedded with the camera service

**Comment by sohnkarlsruhe** [comment]
Okay, thanks for your help
