### ISSUE TITLE
FFmpeg code -2 error

### ISSUE THREAD

**Issue by jbk1988** [hjdhjd/homebridge-doorbird#39]
Hi,

I'm new to this, but I can't get the camera stream to work -- the lock and the light mechanism are fine! This is what I get in the log:

[11/8/2019, 8:15:56 PM] Homebridge is running on port 51095.
[11/8/2019, 8:15:56 PM] DoorBird is running on port 41515.
[11/8/2019, 8:15:56 PM] Please add [DoorBird] manually in Home app. Setup Code: XXX
[11/8/2019, 8:15:56 PM] [DoorBird]  DoorBird is listening on port 5005
[11/8/2019, 8:15:56 PM] Default Camera is running on port 39205.
[11/8/2019, 8:15:56 PM] Please add [Default Camera] manually in Home app. Setup Code: XXX

I've removed the user and password and IP, but what is wrong with the config?

Thanks for your help!

 "platforms": [
        {
            "platform": "DoorBird",
            "cameras": [
                {
                    "name": "DoorBird",
                    "doorbird_ip": "XXX",
                    "doorbird_username": "XXX",
                    "doorbird_password": "XXX",
                    "cmd_doorbell": "wget -q 'http://doorbird-ip/bha-api/notification.cgi?http-user=XXX&http-password=XXX&event=doorbell&subscribe=1&url=http://homebridge-ip:5005/doorbell.html'",
                    "cmd_motionsensor": "wget -q 'http://doorbird-ip/bha-api/notification.cgi?http-userXXX&http-password=XXX&event=motionsensor&subscribe=1&url=http://homebridge-ip:5005/motion.html'",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://XXX:XXX@192.168.7.218:8557/mpeg/media.amp",
                        "stillImageSource": "-i http://XXX:80/bha-api/image.cgi?http-user=XXX&http-password=XXX",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 15,
                        "port": 5005
                    }
                }
            ]
        },
        {
            "name": "Camera ffmpeg",
            "cameras": [
                {
                    "name": "Default Camera",
                    "videoConfig": {
                        "source": "-re -i  rtsp://XXX:7zJaeEwJt7@XXX:8557/mpeg/media.amp",
                        "stillImageSource": "-i http://XXX:80/bha-api/image.cgi?http-user=XXX&http-password=XXX",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 10,
                        "maxBitrate": 300,
                        "vcodec": "libx264",
                        "packetSize": 1316,
                        "audio": true,
                        "debug": false
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }
    ],
    "accessories": []
}

**Comment by brownad** [comment]
Ffmpeg installed?

**Comment by jbk1988** [comment]
Does that have to be done separately from the first MMPEG plug-in in your instructions? I’m running homebridge on Portianer within Home Assistant. Thanks for your response!

**Comment by brownad** [comment]
You would need ffmpeg installed first yes. Did you do that?

**Comment by jbk1988** [comment]
I attempted to do that within Portainer -- because of the nature of Hassio, I'm not sure I can install it natively. This is what I did -- is this a workable setup or do I need to run on a separate Pi?

Thanks again for your help.

I was using this as a guide and trying to see if I could use that as a basis to connect them:
https://community.home-assistant.io/t/tutorial-add-homebridge-to-hass-io-using-portainer/140423

<img width="1023" alt="Screen Shot 2019-11-10 at 12 50 23 PM" src="https://user-images.githubusercontent.com/48226780/68550576-d6277f80-03b8-11ea-8dcc-f4e57ed6f8a3.png">

**Comment by jbk1988** [comment]
I attempted to link the containers together, but again, I'm new to dealing with this, so I'm totally unsure if this process can work.
<img width="1580" alt="Screen Shot 2019-11-10 at 12 56 55 PM" src="https://user-images.githubusercontent.com/48226780/68550670-ae84e700-03b9-11ea-8f0a-bf4744354b22.png">
![Uploading Screen Shot 2019-11-10 at 12.57.06 PM.png…]()

**Comment by jbk1988** [comment]
<img width="1629" alt="Screen Shot 2019-11-10 at 12 57 06 PM" src="https://user-images.githubusercontent.com/48226780/68550676-c2304d80-03b9-11ea-99a7-7a5925a18fc8.png">

**Comment by jbk1988** [comment]
<img width="1381" alt="Screen Shot 2019-11-10 at 1 01 30 PM" src="https://user-images.githubusercontent.com/48226780/68550747-8fd32000-03ba-11ea-98c5-f8ca62aaa5a5.png">

**Comment by jbk1988** [comment]
<img width="1395" alt="Screen Shot 2019-11-10 at 1 01 14 PM" src="https://user-images.githubusercontent.com/48226780/68550748-95c90100-03ba-11ea-8ba6-248b73462900.png">

**Comment by jbk1988** [comment]
I failed to put a comma in the container for FFMPEG :) So that part is fixed.

Now, I'm just getting a ERROR: FFmpeg exited with code 1

**Comment by jbk1988** [comment]
I solved it by getting a separate Pi just for Homebridge :) Thank you. Final question, is there a way to enable it to push notifications into HomeKit? I registered the HTTP call in DoorBird, but I don't get pushes -- everything else works perfectly though.

**Comment by brownad** [comment]
That’s good progress.  So to enable push on doorbell then click on the video feed, settings, status and notifications, allow notifications , on.

If you don’t receive any check your http config is correct run a test against the endpoint you made and check the logs

That’s all there is to it

**Comment by jbk1988** [comment]
Thank you! That's all correct, so I must be messing up the end point. Can you give me any pointers on that? I appreciate your guidance as I figure this out.

**Comment by brownad** [comment]
Follow the instructions carefully about the config 

wget -q 'http://doorbird-ip/bha-api/notification.cgi?http-user=XXX&http-password=XXX&event=doorbell&subscribe=1&url=http://homebridge-ip:5005/doorbell.html'
So the endpoint is the IP of your homebridge server with a port 5005 and the url shown above if you hit that directly it will test it out if that works then wire it up with doorbird to send notifications to it on he event

**Comment by uspino2** [comment]
Don't know if this might be related, but I get this error when attempting to watch video:

```
[11/15/2019, 8:12:33 AM] [DoorBird] Start streaming video from DoorBird with 1280x720@299kBit
[11/15/2019, 8:12:33 AM] [DoorBird] An error occurs while making stream request
[11/15/2019, 8:12:33 AM] [DoorBird] ERROR: FFmpeg exited with code -4058

```
And this when trying to get a snapshot:

```
[11/15/2019, 8:08:43 AM] [DoorBird] Snapshot from DoorBird at 480x270
[11/15/2019, 8:08:43 AM] [DoorBird] An error occurs while making snapshot request
```

Running Homebridge on Windows. Ffmpeg camera plugin is installed. Should ffmpeg executable be in any specific directory? Any suggestion?

**Comment by brownad** [comment]
That’s going to be down to how ffmpeg was setup and installed.  Not an expert in that best to follow instructions on ffmpeg or look a the ffmpeg plugin has some good notes

**Comment by jbk1988** [comment]
> Follow the instructions carefully about the config wget -q 'http://doorbird-ip/bha-api/notification.cgi?http-user=XXX&http-password=XXX&event=doorbell&subscribe=1&url=http://homebridge-ip:5005/doorbell.html' So the endpoint is the IP of your homebridge server with a port 5005 and the url shown above if you hit that directly it will test it out if that works then wire it up with doorbird to send notifications to it on he event
> […](#)
> Sent from my iPhone
> On 15 Nov 2019, at 06:20, jbk1988 ***@***.***> wrote: Thank you! That's all correct, so I must be messing up the end point. Can you give me any pointers on that? I appreciate your guidance as I figure this out. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you for this! 

So, I did this as described:

 "cmd_doorbell": "wget -q 'http://xxxDoorbirdIP/bha-api/notification.cgi?http-user=XXX&http-password=XXX&event=doorbell&subscribe=1&url=http://HomeBridgeIP:5005/doorbell.html'",

The port is 5005 on HomeBridge.

In Doorbird, under user rules, I have given the user permission for everything.

In HTTP calls, I have put in two lines for the http://HomeBridgeIP:5005/doorbell.html & motion.html, respectively.

I can see the steam -- although it is more of a still image as the buffer takes too long, can this be modified -- and lock/unlock and turn on the IR.

In HomeKit, all notifications are turned on for the Doorbell and Motion -- should the IP address include port 8080 for HomeBridge? What am I doing wrong in this setup?

**Comment by brownad** [comment]
Replace homebridgeip with your actual internal IP address of the running homebridge server and that’s it

**Comment by jbk1988** [comment]
> Replace homebridgeip with your actual internal IP address of the running homebridge server and that’s it
> […](#)

That's what I did -- pulled from Eero. Unfortunately, it doesn't seem to be working. Alas. Is there a way to check what IP address HomeBridge is receiving within HomeBridge? It may be a weird allocation thing. For example, when I run hostname -I, I get two addresses -- one that I'm using, and one that I am not.

**Comment by brownad** [comment]
If you can’t reach the IP address then that’s the problem, need to expose it somehow

**Comment by jbk1988** [comment]
> If you can’t reach the IP address then that’s the problem, need to expose it somehow
> […](#)

It all is working when I SSH into the drive, which is why I presumed that would be the address. Anyway, thanks for your help.

**Comment by brownad** [comment]
I’m not familiar with how you’re running the server but have a look at how to access that IP address, as the plugin setups an endpoint based on the running IP - the. You use that to wire up doorbird to the server for events..

**Comment by memu11** [comment]
If someone uses Docker with a Synology NAS and doesn't get a stream: Open the terminal in docker with the command "sh" and type "apk add ffmpeg" -> Then everything worked for me. Don't know why it's written so complicated everywhere.

**Comment by Gface911** [comment]
Can someone help me. I’m having issues getting the video to show up in HomeKit. But I’m VERY green when it comes to this kinda stuff. I can get like a photo of what is happening but when i click on it then i get this
![IMG_3509](https://github.com/hjdhjd/homebridge-doorbird/assets/166780914/da125110-3d02-4bfa-9220-91f1354167a7)

I would even like hire someone to help me figure this out.
