### ISSUE TITLE
A way to change notification sound ?

### ISSUE THREAD

**Issue by Vinisz** [hjdhjd/homebridge-doorbird#42]
Hi, I have notifcations on doorbell press working just fine, using http://homebridge-ip:5005/doorbell.html.
However, I would like to have another sound, (like ding-dong or something)
Is this possible ?

I see something like curl -X POST -d 'ding=dong&dong=ding' http://IP_OF_HOMEBRIDGE_RUNNING_DEVICE:PORT_DEFINED_IN_CONFIG in homebridge-videodoorbell but I do not known if that works here as well or how to use it with a normal http get or post.

Thanks in advance.

**Comment by brownad** [comment]
Sorry, doesn't set sounds on iOS, you get what Apple provide for notifications.  Not something the plugin can change.  the curl example is a way to trigger something else on the event e.g. you want another system to know there's a ring or motion
