### ISSUE TITLE
D21DKH and multi-tenant building

### ISSUE THREAD

**Issue by TDT1969** [hjdhjd/homebridge-doorbird#421]
I’ve just found this plugin and am trying to understand if it will work with my situation.

Background: We have a DoorBird D21DKH in a small 8-unit apartment building.  I am an admin of the DoorBird, so have full access.  However, the DoorBird is on it’s own network/internet connection.  I have a DoorBird indoor station that’s hardwired (Ethernet) in my apartment.

Question: Will this plug-in work in my situation?  My areas of concern are 1) multi-user — can I make it just work for visitors who ring my apartment?, and 2) network — if it’s not on the same network as my HomeBridge/RPi, will it work?  If not, does my indoor station that has Wi-Fi and is hard-wired to the DoorBird present any opportunities to bridge?

Finally, I found this (but it was over my head): https://github.com/RJ/doorbird-mdns-vlan-subnet-bridge

Thanks in advance for any advice.

**Comment by TDT1969** [comment]
Any advice would be much appreciated!

**Comment by hjdhjd** [comment]
If the plugin can get to the IP of the Doorbird, then the plugin should work. The fact that it’s multitenant isn’t really germane to the plugin…that’s a distinction that doesn’t exist here per se. What matters is:

1. Can the plugin access the IP of the Doorbird.
2. Does the username have permissions for the relays / doors you want to trigger.

Those are really the only variables here…Doorbird has a permissions system, essentially, to determine which doors/relays a particular user can access. I imagine if you try it with the right permissions, things should work. At the end of the day, experimentation is your friend so give it a try. :smile:

**Comment by TDT1969** [comment]
Very helpful, thanks.  Sounds like I need to use the Ethernet interface of my RPi for my local stuff and attempt to get the Wi-Fi on the DoorBird network — and ensure no IP duplication.
