### ISSUE TITLE
No Video, but Still working

### ISSUE THREAD

**Issue by Tscherno** [hjdhjd/homebridge-doorbird#43]
Hi,

i just set up the Plugin with my new Doorbird. It shows in the Home App, current Still image works fine. But as soon as i try to see the live video it spins... until "No Answer from camera".

Log isnt very useful:
[3/29/2020, 1:59:38 PM] [DoorBird] Snapshot from DoorBird at 480x270
[3/29/2020, 1:59:39 PM] [DoorBird] Start streaming video from DoorBird with 1280x720@299kBit
[3/29/2020, 2:00:09 PM] [DoorBird] Stopped streaming

The RTSP URL i provided works fine with VLC.

**Comment by brownad** [comment]
Show the URL without your creds please

**Comment by Tscherno** [comment]
rtsp://bla:blubb@doorbird-einfahrt.fritz.box:8557/mpeg/media.amp

**Comment by brownad** [comment]
What command do you use before it?

Can you try the mjpeg one instead I have noticed rtsp can be up and down from doorbird

Out of interest is that a new format with fritz.box are you setting or using a DNS?

Add command eg

"source":"-re -i rtsp://<username>:<password>@<doorbird_ip>:554/mpeg/media.amp",

**Comment by Tscherno** [comment]
I used the one provided in the sample: "-rtsp_transport tcp -re -i ..."

Is a different URL needed for MJPEG?

fritz.box is the pseudo-domain of the very common german router AVM Fritz!Box. Every local device which is managed by it's DNS/DHCP gets hostname.fritz.box by default. The name resolution works for sure, because the still image has the same hostname...

**Comment by brownad** [comment]
Still and issue @Tscherno ?

**Comment by naorth** [comment]
Hey,
I seem to be having the same problem. I'm on a raspberry pi 4 and when I try to stream the video from the home app it never loads and eventually answers with "No response". Still images work good though.
`11/06/2020,` 14:52:38 [Doorbird] Start streaming video from Doorbird with 1280:720@15fps (299kBit)
11/06/2020, 14:53:10 [Doorbird] Stopped streaming`

**Comment by brownad** [comment]
Are you using the latest?  With all the changes included does require a removal of old doorbird plugin

**Comment by naorth** [comment]
Sorry spoke too fast. Did a bit of digging and realised that it had nothing to do with the plugin but was just a network setup problem.

**Comment by brownad** [comment]
Awesome
