### ISSUE TITLE
Additional relays and sensors

### ISSUE THREAD

**Issue by mapkyxa** [hjdhjd/homebridge-doorbird#44]
Is it possible to add more then just 1 relay and sensors from io extender?

**Comment by andreasgruener** [comment]
I think this would be a great extenstion.

I checked the Doorbird API document (https://www.doorbird.com/downloads/api_lan.pdf?rev=0.27 See page 12)
There should be the additional information for the EA Controller and the relais.
`GET http://<doorbird-ip>/bha-api/open-door.cgi?r=<6-letter-code of controller>@<number-of-relais>&http-user=<user>&http-password=<secret>>`
 
For me the URL is:   
`GET http://192.168.88.100/bha-api/open-door.cgi?r=gggggg@1&http-user=***&http-password=***`

Looking at the code in index.js Linie 97 I assume the change should be something along the lines:
```
if ( self.has_eacontroller ) {
    self.lockUrl = "http://" + self.ip + self.open + self.eacontroller + "@" + self.relaisno + "&http-user=" + self.username + "&http-password=" + self.password
} else {
    ... existing
}
```
The config should be extended in line 85:
```
   self.has_eacontroller = cameraConfig.has_eacontroller;
   self.eacontroller = cameraConfig.eacontroller;
   self.relaisno = cameraConfig.relaisno;
```

config.json:
```
    "has_eacontroller": true,
    "eacontroller": "ghjasdk",
    "relaisno": "1",
```

Thanks @brownad your plugin worked out of the box. Great work & help!

**Comment by brownad** [comment]
Want to make a PR nice idea

**Comment by brownad** [comment]
Want to close this now @andreasgruener ?

**Comment by andreasgruener** [comment]
If I have time over the next few days/weeks. I might add additional sensors / relays as services. 
A sample relay use case would be to open the garden door via the second relay or a reed switch as a sensor for an open door/window. 
This would match the request/requirement from @mapkyxa

**Comment by hjdhjd** [comment]
I posted a pull request this evening providing for full relay and peripheral support. Feel free to test and take a look. A number of changes to configuration since we do discovery of all relays and peripherals at startup...should simplify some things.

**Comment by hjdhjd** [comment]
#61

**Comment by mapkyxa** [comment]
I will try it all out next week when I will have one of the relay modules on hand again. Will update you on a result

**Comment by brownad** [comment]
@mapkyxa do close if you're happy, publishing shortly
