### ISSUE TITLE
Doorbell Tile

### ISSUE THREAD

**Issue by 07charli** [hjdhjd/homebridge-doorbird#440]
Hi,

Is it possible to have the doorbell tile show up in Homekit. Currently I am getting the motion sensor, infrared light and door lock tiles showing up. I was trying to set up automations when the actual doorbell rang, however there is no 'doorbell' tile option. There is a 'Homebridge Doorbell' tile on the homebridge dashboard, but it doesn't show up in Home app.

Cheers

**Comment by michaelyork** [comment]
You need to select "Show as separate tiles" on one of the other accessories (motion, IR) to see the doorbell tile. A little confusing (it's an Apple Home app UX quirk).
