### ISSUE TITLE
Question: 2-Way Audio

### ISSUE THREAD

**Issue by Naruk-TUBK** [hjdhjd/homebridge-doorbird#442]
Is the 2-Way Audio feature still/currently in implementation? The main Readme states that only 1-way audio is supported right now

**Comment by hjdhjd** [comment]
There have been API issues on the Doorbird end...I'll revisit this at some point in the future, I believe they're addressed now. Thanks!

**Comment by stephanlinke87** [comment]
Any chance this will be implemented? :)
