### ISSUE TITLE
Homebridge 1.0.x error message

### ISSUE THREAD

**Issue by dsully** [hjdhjd/homebridge-doorbird#45]
With Homebridge 1.0.x, there is an error message in the logs:

    May  1 09:48:55 server homebridge[732140]: [5/1/2020, 9:48:55 AM] [DoorBird] Initializing DoorBird platform...
    May  1 09:48:55 server homebridge[732140]: [5/1/2020, 9:48:55 AM] One of your plugins incorrectly registered an external accessory using the platform name (DoorBird) and not the plugin identifier. Please report this to the developer!
    May  1 09:48:55 server homebridge[732140]: [5/1/2020, 9:48:55 AM] DoorBird is running on port 20183.`

**Comment by brownad** [comment]
Check the plugin name used in your config matches up to the example config

**Comment by CameronVIE** [comment]
Same error here!
DoorBird does not show up when i try to add it in HKit.


platforms": [
        {
            "platform": "DoorBird",
            "cameras": [
                {
                    "name": "DoorBird",
                    "doorbird_ip": "",
                    "doorbird_username": "",
                    "doorbird_password": "",
                    "cmd_doorbell": "",
                    "cmd_motionsensor": "",
                    "videoConfig": {
                        "source": "-re -f mjpeg -i http://yyyyyyyyyyy:xxxxxxxxxx@aaa.bbb.ccc.ddd/bha-api/video.cgi",
                        "stillImageSource": "-i http://aaa.bbb.ccc.ddd:80/bha-api/image.cgi?http-user=yyyyyyy&http-password=xxxxxxxxx",
                        "maxStreams": 4,
                        "maxWidth": 800,
                        "maxHeight": 600,
                        "maxFPS": 15,
                        "port": 5005
                    }
                }
            ]
        },

thanx alot

**Comment by peer69** [comment]
Same here. Plugin still works as before though.

**Comment by mrhund** [comment]
Platform and Name are not allowed to be the same string. Try different ones.

**Comment by peer69** [comment]
While the sample config file shows platform and name as the same in my config those are different. This doesn’t seem to be the issue for me.

**Comment by mrhund** [comment]
Sorry, you are right - found the issue in the code and fixed it for me. Will create a Pull Request.

**Comment by brownad** [comment]
published v0.0.7 thanks @mrhund (again)

**Comment by brownad** [comment]
@dsully feel free to close if you're happy with the changes. Thanks @mrhund for smashing this one

**Comment by peer69** [comment]
Works for me. Thank you guys for fixing this so fast!

**Comment by dsully** [comment]
Looks good here too.
