### ISSUE TITLE
Possibility to trigger lights

### ISSUE THREAD

**Issue by naorth** [hjdhjd/homebridge-doorbird#50]
Hey, I have lights that are hooked up to my doorbird. I was wondering if there would be any way of being able to trigger them through the home app.

**Comment by brownad** [comment]
Hi

How are the lights hooked up?  Is this something new with doorbird to devices?

**Comment by naorth** [comment]
The lights are hooked up just like a gate trigger
![IMG_7450](https://user-images.githubusercontent.com/54583836/81573454-cf4bea80-93a4-11ea-9c62-570f833f7df6.jpeg)

**Comment by brownad** [comment]
Got it so it’s a relay of sorts. But is there an off state from the app? Does it work similar to the lock whereby it just opens it but never knows if open or closed?

**Comment by naorth** [comment]
It works exactly like a lock. It just triggers it but never knows whether it’s on or off.

**Comment by brownad** [comment]
Yeah that isn’t ideal for a light you’d want to know the state on load eg you open the app and know if it was active or not. The lock is somewhat ok as you trigger it to open and that’s that it resets it state to locked after a few minutes.

Although not ideal have you thought of hue lights then you can automate off the sensors on the plugin. That works well for me either motion or doorbell ring..

**Comment by naorth** [comment]
Yeah it would be better that way but I don’t have a Philips hue setup. For the moment, do you have any ideas on how I would be able to trigger the lights?

**Comment by naorth** [comment]
Figured it out. Since it was just set up as a relay I simply triggered it in the exact same way as I would trigger a gate.

**Comment by brownad** [comment]
Ok great you have it working for your needs?

**Comment by naorth** [comment]
Yep. I installed the plugin http-switch which lets me trigger the lights and keeps the state as long as I don’t trigger  it through doorbird.

**Comment by brownad** [comment]
Ok cool yeah that’s a nice way I’ll have a look to extend the plugin for more relays
