### ISSUE TITLE
Will 2-way audio ever be implemented ?

### ISSUE THREAD

**Issue by Vinisz** [hjdhjd/homebridge-doorbird#516]
Hi,

Thanks for this great plugin, works perfect, but.... Will 2-way audio ever arrive/be possible ?

**Comment by mbrackjr** [comment]
It's been a while since hjdhjd told us to 'stay tuned'.  I would very, very much welcome this feature to arrive, but not counting on it anymore.

**Comment by hjdhjd** [comment]
It has been a while…that’s more than fair. When I have the time, I will…but I can’t commit to a time horizon. These are labors of love, and other priorities compete for time and attention.

TL;DR: it’s on my radar, but it will come eventually as time and priorities allows. Thanks.
