### ISSUE TITLE
Doorbird doesn't reply after update

### ISSUE THREAD

**Issue by moerpel** [hjdhjd/homebridge-doorbird#71]
After the update to the recent version using homebridge-config-ui-x my homekit says the doorbird doesn't reply. 
The existing config was gone. 
I reconfigured the plugin but now the Doorbird doesn't appear at all when I try to add it as new device.

**Comment by hjdhjd** [comment]
Follow these steps if you’re on 0.3.0 or beyond:

* Delete the Doorbird using the Home app.
* Shutdown homebridge.
* Then clear out your persist and accessories directories:
— `rm -rf ~/.homebridge/persist`
— `rm -rf ~/.homebridge/accessories`
* Restart homebridge.
* Add the Doorbird in the Home app.
* Enjoy. :smile:

The way Doorbirds are identified to HomeKit has been updated to scale to multiple Doorbird situations and eliminate future name collision issues. This should be a one-time change. Thanks.

**Comment by CameronVIE** [comment]
I went back to 0.0.8
npm install homebridge-doorbird@0.0.8

I would like to have better infos before i go to 0.3.0 on what you mean by "delete the Doorbird using the Home app" ... 
HomeApp does not respond due to failing start of HomeBridge ...
So, how to delete Doorbird?
Thanx for help!

**Comment by moerpel** [comment]
I solved it finally by deleting the existing Doorbird pairing under Unpair Bridges / Cameras / TVs / External Accessories under Homebridge settings in homebridge config ui x.
Thanks for your help!

**Comment by moerpel** [comment]
... and I updated to 0.3.1

**Comment by hjdhjd** [comment]
For future reference - the GUI action and the ones I wrote above are effectively the same. The only difference being that the GUI option is a prettier and more surgical approach to only remove certain accessories from the cache. Glad it's working. Good luck.
