### ISSUE TITLE
Doorbell button as trigger

### ISSUE THREAD

**Issue by b8887** [hjdhjd/homebridge-doorbird#72]
Apologies if i'm missing something obvious...I'm new to homebridge.  I don't see the doorbell button exposed in the home app. I'd like to use it as a trigger for automations. I only see the relay, motion, and IR in addition to the camera feed.

**Comment by hjdhjd** [comment]
The doorbell itself is not exposed in HomeKit. You can't build automations purely on the doorbell event as there is no doorbell event currently exposed.
