### ISSUE TITLE
Automate Door Lock?

### ISSUE THREAD

**Issue by jbk1988** [hjdhjd/homebridge-doorbird#73]
Is there a way to automate the relay to lock after a set period of time after unlocking?

For my door gate, not driveway, it’s on an electric strike - and when i play with that, I was curious if this plugin provided latitude to do it.

**Comment by hjdhjd** [comment]
I’d look into other homebridge plugins like [homebridge-delay-switch](https://github.com/nitaybz/homebridge-delay-switch) to do something like this.

There are other similar plugins to the above...google. :smile:
