### ISSUE TITLE
Question about installation

### ISSUE THREAD

**Issue by Fulltopuk** [hjdhjd/homebridge-doorbird#74]
Hi 

Great plug in, everything works apart from stream so my question is does FFMPEG still need to be install for this plug in to work fully?

I also have a I/O unit on my system so can feedback how it works

Thanks

**Comment by Fulltopuk** [comment]
Anyone?  Sorry if this seems to be a stupid question but wondering if ffmpeg needs to be installed separately as the guide doesn't specify.  PS I installed it on Hoobs

**Comment by brownad** [comment]
Not with the latest, it installs it for you

**Comment by Fulltopuk** [comment]
Thanks
