### ISSUE TITLE
DoorBird Chime

### ISSUE THREAD

**Issue by jbk1988** [hjdhjd/homebridge-doorbird#75]
Has anyone else had issues with the DoorBird Chime not working in this setup? Does it need to be setup as a separate HTTP call?

**Comment by brownad** [comment]
Works fine for me.  There’s really no configuration to add DoorBird Chime into this setup, it hangs off the DoorBird app as an accessory as it did before.  No change.

**Comment by hjdhjd** [comment]
Likewise - I have several Chime devices. The Chimes are configured to speak with the Doorbird. There's no interaction model for them with this plugin. I'd validate that the chimes are working correctly with Doorbird, independent of this plugin.
