### ISSUE TITLE
Security warning?

### ISSUE THREAD

**Issue by hjdhjd** [hjdhjd/homebridge-doorbird#9]
Tried to do a clean install of homebridge-doorbird:

npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

Thoughts?

**Comment by brownad** [comment]
Just a warm on the npm module - one of the dependencies nothing to worry about

**Comment by brownad** [comment]
Closing this one
